// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.3
// source: collection/collection.proto

package collection

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCollectionCreateCollectionRecord = "/api.collection.Collection/CreateCollectionRecord"
const OperationCollectionListCollectionRecord = "/api.collection.Collection/ListCollectionRecord"

type CollectionHTTPServer interface {
	CreateCollectionRecord(context.Context, *CollectionRecord) (*Empty, error)
	ListCollectionRecord(context.Context, *ListCollectionRecordReq) (*ListCollectionRecordResp, error)
}

func RegisterCollectionHTTPServer(s *http.Server, srv CollectionHTTPServer) {
	r := s.Route("/")
	r.POST("/collection/record", _Collection_CreateCollectionRecord0_HTTP_Handler(srv))
	r.GET("/collection/record", _Collection_ListCollectionRecord0_HTTP_Handler(srv))
}

func _Collection_CreateCollectionRecord0_HTTP_Handler(srv CollectionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CollectionRecord
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCollectionCreateCollectionRecord)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCollectionRecord(ctx, req.(*CollectionRecord))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

func _Collection_ListCollectionRecord0_HTTP_Handler(srv CollectionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCollectionRecordReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCollectionListCollectionRecord)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCollectionRecord(ctx, req.(*ListCollectionRecordReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCollectionRecordResp)
		return ctx.Result(200, reply)
	}
}

type CollectionHTTPClient interface {
	CreateCollectionRecord(ctx context.Context, req *CollectionRecord, opts ...http.CallOption) (rsp *Empty, err error)
	ListCollectionRecord(ctx context.Context, req *ListCollectionRecordReq, opts ...http.CallOption) (rsp *ListCollectionRecordResp, err error)
}

type CollectionHTTPClientImpl struct {
	cc *http.Client
}

func NewCollectionHTTPClient(client *http.Client) CollectionHTTPClient {
	return &CollectionHTTPClientImpl{client}
}

func (c *CollectionHTTPClientImpl) CreateCollectionRecord(ctx context.Context, in *CollectionRecord, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "/collection/record"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCollectionCreateCollectionRecord))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *CollectionHTTPClientImpl) ListCollectionRecord(ctx context.Context, in *ListCollectionRecordReq, opts ...http.CallOption) (*ListCollectionRecordResp, error) {
	var out ListCollectionRecordResp
	pattern := "/collection/record"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCollectionListCollectionRecord))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
