// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: collector/collector.proto

package collector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Collector_ReportImmediately_FullMethodName  = "/api.collector.Collector/ReportImmediately"
	Collector_SetReportInterval_FullMethodName  = "/api.collector.Collector/SetReportInterval"
	Collector_GetDeviceStreamLog_FullMethodName = "/api.collector.Collector/GetDeviceStreamLog"
)

// CollectorClient is the client API for Collector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorClient interface {
	ReportImmediately(ctx context.Context, in *ReportImmediatelyReq, opts ...grpc.CallOption) (*ReportImmediatelyResp, error)
	SetReportInterval(ctx context.Context, in *SetReportIntervalReq, opts ...grpc.CallOption) (*SetReportIntervalResp, error)
	GetDeviceStreamLog(ctx context.Context, in *GetDeviceStreamLogReq, opts ...grpc.CallOption) (Collector_GetDeviceStreamLogClient, error)
}

type collectorClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorClient(cc grpc.ClientConnInterface) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) ReportImmediately(ctx context.Context, in *ReportImmediatelyReq, opts ...grpc.CallOption) (*ReportImmediatelyResp, error) {
	out := new(ReportImmediatelyResp)
	err := c.cc.Invoke(ctx, Collector_ReportImmediately_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) SetReportInterval(ctx context.Context, in *SetReportIntervalReq, opts ...grpc.CallOption) (*SetReportIntervalResp, error) {
	out := new(SetReportIntervalResp)
	err := c.cc.Invoke(ctx, Collector_SetReportInterval_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) GetDeviceStreamLog(ctx context.Context, in *GetDeviceStreamLogReq, opts ...grpc.CallOption) (Collector_GetDeviceStreamLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &Collector_ServiceDesc.Streams[0], Collector_GetDeviceStreamLog_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorGetDeviceStreamLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Collector_GetDeviceStreamLogClient interface {
	Recv() (*GetDeviceStreamLogResp, error)
	grpc.ClientStream
}

type collectorGetDeviceStreamLogClient struct {
	grpc.ClientStream
}

func (x *collectorGetDeviceStreamLogClient) Recv() (*GetDeviceStreamLogResp, error) {
	m := new(GetDeviceStreamLogResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectorServer is the server API for Collector service.
// All implementations must embed UnimplementedCollectorServer
// for forward compatibility
type CollectorServer interface {
	ReportImmediately(context.Context, *ReportImmediatelyReq) (*ReportImmediatelyResp, error)
	SetReportInterval(context.Context, *SetReportIntervalReq) (*SetReportIntervalResp, error)
	GetDeviceStreamLog(*GetDeviceStreamLogReq, Collector_GetDeviceStreamLogServer) error
	mustEmbedUnimplementedCollectorServer()
}

// UnimplementedCollectorServer must be embedded to have forward compatible implementations.
type UnimplementedCollectorServer struct {
}

func (UnimplementedCollectorServer) ReportImmediately(context.Context, *ReportImmediatelyReq) (*ReportImmediatelyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportImmediately not implemented")
}
func (UnimplementedCollectorServer) SetReportInterval(context.Context, *SetReportIntervalReq) (*SetReportIntervalResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetReportInterval not implemented")
}
func (UnimplementedCollectorServer) GetDeviceStreamLog(*GetDeviceStreamLogReq, Collector_GetDeviceStreamLogServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDeviceStreamLog not implemented")
}
func (UnimplementedCollectorServer) mustEmbedUnimplementedCollectorServer() {}

// UnsafeCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServer will
// result in compilation errors.
type UnsafeCollectorServer interface {
	mustEmbedUnimplementedCollectorServer()
}

func RegisterCollectorServer(s grpc.ServiceRegistrar, srv CollectorServer) {
	s.RegisterService(&Collector_ServiceDesc, srv)
}

func _Collector_ReportImmediately_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportImmediatelyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).ReportImmediately(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collector_ReportImmediately_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).ReportImmediately(ctx, req.(*ReportImmediatelyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_SetReportInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReportIntervalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).SetReportInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collector_SetReportInterval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).SetReportInterval(ctx, req.(*SetReportIntervalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_GetDeviceStreamLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDeviceStreamLogReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServer).GetDeviceStreamLog(m, &collectorGetDeviceStreamLogServer{stream})
}

type Collector_GetDeviceStreamLogServer interface {
	Send(*GetDeviceStreamLogResp) error
	grpc.ServerStream
}

type collectorGetDeviceStreamLogServer struct {
	grpc.ServerStream
}

func (x *collectorGetDeviceStreamLogServer) Send(m *GetDeviceStreamLogResp) error {
	return x.ServerStream.SendMsg(m)
}

// Collector_ServiceDesc is the grpc.ServiceDesc for Collector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.collector.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportImmediately",
			Handler:    _Collector_ReportImmediately_Handler,
		},
		{
			MethodName: "SetReportInterval",
			Handler:    _Collector_SetReportInterval_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDeviceStreamLog",
			Handler:       _Collector_GetDeviceStreamLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collector/collector.proto",
}
