// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: notify/notify.proto

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Notify_NotifyTestEmail_FullMethodName     = "/api.notify.Notify/NotifyTestEmail"
	Notify_NotifyDeviceOnline_FullMethodName  = "/api.notify.Notify/NotifyDeviceOnline"
	Notify_NotifyDeviceOffline_FullMethodName = "/api.notify.Notify/NotifyDeviceOffline"
)

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifyClient interface {
	NotifyTestEmail(ctx context.Context, in *NotifyTestEmailReq, opts ...grpc.CallOption) (*Empty, error)
	NotifyDeviceOnline(ctx context.Context, in *NotifyDeviceOnlineReq, opts ...grpc.CallOption) (*Empty, error)
	NotifyDeviceOffline(ctx context.Context, in *NotifyDeviceOfflineReq, opts ...grpc.CallOption) (*Empty, error)
}

type notifyClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyClient(cc grpc.ClientConnInterface) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) NotifyTestEmail(ctx context.Context, in *NotifyTestEmailReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Notify_NotifyTestEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) NotifyDeviceOnline(ctx context.Context, in *NotifyDeviceOnlineReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Notify_NotifyDeviceOnline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) NotifyDeviceOffline(ctx context.Context, in *NotifyDeviceOfflineReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Notify_NotifyDeviceOffline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
// All implementations must embed UnimplementedNotifyServer
// for forward compatibility
type NotifyServer interface {
	NotifyTestEmail(context.Context, *NotifyTestEmailReq) (*Empty, error)
	NotifyDeviceOnline(context.Context, *NotifyDeviceOnlineReq) (*Empty, error)
	NotifyDeviceOffline(context.Context, *NotifyDeviceOfflineReq) (*Empty, error)
	mustEmbedUnimplementedNotifyServer()
}

// UnimplementedNotifyServer must be embedded to have forward compatible implementations.
type UnimplementedNotifyServer struct {
}

func (UnimplementedNotifyServer) NotifyTestEmail(context.Context, *NotifyTestEmailReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyTestEmail not implemented")
}
func (UnimplementedNotifyServer) NotifyDeviceOnline(context.Context, *NotifyDeviceOnlineReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyDeviceOnline not implemented")
}
func (UnimplementedNotifyServer) NotifyDeviceOffline(context.Context, *NotifyDeviceOfflineReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyDeviceOffline not implemented")
}
func (UnimplementedNotifyServer) mustEmbedUnimplementedNotifyServer() {}

// UnsafeNotifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServer will
// result in compilation errors.
type UnsafeNotifyServer interface {
	mustEmbedUnimplementedNotifyServer()
}

func RegisterNotifyServer(s grpc.ServiceRegistrar, srv NotifyServer) {
	s.RegisterService(&Notify_ServiceDesc, srv)
}

func _Notify_NotifyTestEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyTestEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).NotifyTestEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notify_NotifyTestEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).NotifyTestEmail(ctx, req.(*NotifyTestEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_NotifyDeviceOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyDeviceOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).NotifyDeviceOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notify_NotifyDeviceOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).NotifyDeviceOnline(ctx, req.(*NotifyDeviceOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_NotifyDeviceOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyDeviceOfflineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).NotifyDeviceOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notify_NotifyDeviceOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).NotifyDeviceOffline(ctx, req.(*NotifyDeviceOfflineReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Notify_ServiceDesc is the grpc.ServiceDesc for Notify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notify.Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyTestEmail",
			Handler:    _Notify_NotifyTestEmail_Handler,
		},
		{
			MethodName: "NotifyDeviceOnline",
			Handler:    _Notify_NotifyDeviceOnline_Handler,
		},
		{
			MethodName: "NotifyDeviceOffline",
			Handler:    _Notify_NotifyDeviceOffline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify/notify.proto",
}
