// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.3
// source: mail/mail.proto

package mail

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMailSendMail = "/api.mail.Mail/SendMail"

type MailHTTPServer interface {
	SendMail(context.Context, *SendMailReq) (*Empty, error)
}

func RegisterMailHTTPServer(s *http.Server, srv MailHTTPServer) {
	r := s.Route("/")
	r.POST("/mail/send", _Mail_SendMail0_HTTP_Handler(srv))
}

func _Mail_SendMail0_HTTP_Handler(srv MailHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMailReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMailSendMail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMail(ctx, req.(*SendMailReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

type MailHTTPClient interface {
	SendMail(ctx context.Context, req *SendMailReq, opts ...http.CallOption) (rsp *Empty, err error)
}

type MailHTTPClientImpl struct {
	cc *http.Client
}

func NewMailHTTPClient(client *http.Client) MailHTTPClient {
	return &MailHTTPClientImpl{client}
}

func (c *MailHTTPClientImpl) SendMail(ctx context.Context, in *SendMailReq, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "/mail/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMailSendMail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
