/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "proto/collector/collector.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(api_collector_HeartbeatPayload, api_collector_HeartbeatPayload, AUTO)


PB_BIND(api_collector_LogPayload, api_collector_LogPayload, AUTO)


PB_BIND(api_collector_Empty, api_collector_Empty, AUTO)


PB_BIND(api_collector_SetReportIntervalPayload, api_collector_SetReportIntervalPayload, AUTO)


PB_BIND(api_collector_GeoPoint, api_collector_GeoPoint, AUTO)


PB_BIND(api_collector_ReportPayload, api_collector_ReportPayload, AUTO)


PB_BIND(api_collector_Message, api_collector_Message, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

