// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package captcha

import (
	"github.com/I-m-Surrounded-by-IoT/backend/conf"
	"github.com/I-m-Surrounded-by-IoT/backend/internal/registry"
	captcha2 "github.com/I-m-Surrounded-by-IoT/backend/internal/server/captcha"
	"github.com/I-m-Surrounded-by-IoT/backend/service/captcha"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(grpcServerConfig *conf.GrpcServerConfig, confRegistry *conf.Registry, captchaConfig *conf.CaptchaConfig, redisConfig *conf.RedisConfig, kafkaConfig *conf.KafkaConfig, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistry(confRegistry)
	captchaService := captcha.NewCaptchaService(captchaConfig, kafkaConfig, registrar, redisConfig)
	grpcGatewayServer := captcha2.NewCaptchaServer(grpcServerConfig, captchaService)
	app := newApp(logger, grpcGatewayServer, registrar)
	return app, func() {
	}, nil
}
