version: "3.3"
services:
  web:
    image: "zijiren/backend:latest"
    container_name: web
    restart: unless-stopped
    ports:
      - "9500:8080"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=${ETCD_ENDPOINT}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - WEB_JWT_SECRET=${WEB_JWT_SECRET}
      - WEB_JWT_EXPIRE=${WEB_JWT_EXPIRE}
    command: web

  log:
    image: "zijiren/backend:latest"
    container_name: log
    restart: unless-stopped
    ports:
      - "13000:9000"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=${ETCD_ENDPOINT}
      - GRPC_CUSTOM_ENDPOINT=grpc://${CUSTON_EXTERNAL_IP}:13000
      - DATABASE_AUTOMIGRATE=${DATABASE_AUTOMIGRATE-false}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${LOG_DATABASE_USER}
      - DATABASE_PASSWORD=${LOG_DATABASE_PASSWORD}
      - DATABASE_NAME=${LOG_DATABASE_NAME}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
    command: log

  device:
    image: "zijiren/backend:latest"
    container_name: device
    restart: unless-stopped
    ports:
      - "8500:9000"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=${ETCD_ENDPOINT}
      - GRPC_CUSTOM_ENDPOINT=grpc://${CUSTON_EXTERNAL_IP}:8500
      - DATABASE_AUTOMIGRATE=${DATABASE_AUTOMIGRATE-false}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DEVICE_DATABASE_USER}
      - DATABASE_PASSWORD=${DEVICE_DATABASE_PASSWORD}
      - DATABASE_NAME=${DEVICE_DATABASE_NAME}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - DEVICE_EMQX_API=${DEVICE_EMQX_API}
      - DEVICE_EMQX_APPID=${DEVICE_EMQX_APPID}
      - DEVICE_EMQX_APPSECRET=${DEVICE_EMQX_APPSECRET}
    command: device

  collection:
    image: "zijiren/backend:latest"
    container_name: collection
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=${ETCD_ENDPOINT}
      - GRPC_CUSTOM_ENDPOINT=grpc://${CUSTON_EXTERNAL_IP}:9000
      - DATABASE_AUTOMIGRATE=${DATABASE_AUTOMIGRATE-false}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${COLLECTION_DATABASE_USER}
      - DATABASE_PASSWORD=${COLLECTION_DATABASE_PASSWORD}
      - DATABASE_NAME=${COLLECTION_DATABASE_NAME}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
    command: collection

  user:
    image: "zijiren/backend:latest"
    container_name: user
    restart: unless-stopped
    ports:
      - "12000:9000"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=${ETCD_ENDPOINT}
      - GRPC_CUSTOM_ENDPOINT=grpc://${CUSTON_EXTERNAL_IP}:12000
      - DATABASE_AUTOMIGRATE=${DATABASE_AUTOMIGRATE-false}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${USER_DATABASE_USER}
      - DATABASE_PASSWORD=${USER_DATABASE_PASSWORD}
      - DATABASE_NAME=${USER_DATABASE_NAME}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    command: user

  collector:
    image: "zijiren/backend:latest"
    container_name: collector
    restart: unless-stopped
    ports:
      - "11000:9000"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=${ETCD_ENDPOINT}
      - GRPC_CUSTOM_ENDPOINT=grpc://${CUSTON_EXTERNAL_IP}:11000
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - COLLECTOR_MQTT_ADDR=${COLLECTOR_MQTT_ADDR}
      - COLLECTOR_MQTT_CLIENT_ID=${COLLECTOR_MQTT_CLIENT_ID}
      - COLLECTOR_MQTT_PASSWORD=${COLLECTOR_MQTT_PASSWORD}
    command: collector
