version: '3.3'
services:
  gataway:
    image: 'zijiren/backend:latest'
    container_name: backend-gataway
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=etcd:2379
      - TCP_CUSTOM_ENDPOINT=
    command: gateway
  database:
    image: 'zijiren/backend:latest'
    container_name: backend-database
    restart: unless-stopped
    # ports:
    #   - '9000:9000'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=etcd:2379
      - GRPC_CUSTOM_ENDPOINT=database:9000
      - DATABASE_AUTOMIGRATE=true
      - DATABASE_TYPE=0
      - KAFKA_BROKERS=kafka-0:9092
      - KAFKA_USER=
      - KAFKA_PASSWORD=
    command: database
  collector:
    image: 'zijiren/backend:latest'
    container_name: backend-collector
    restart: unless-stopped
    ports:
      - '10000:8000'
      # - '11000:9000'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINT=etcd:2379
      - TCP_CUSTOM_ENDPOINT=
      - GRPC_CUSTOM_ENDPOINT=collector:9000
      - KAFKA_BROKERS=kafka-0:9092
      - KAFKA_USER=
      - KAFKA_PASSWORD=
    command: collector
