version: '3.3'
services:
  backend:
    image: 'synctvorg/backend:latest'
    container_name: backend
    restart: unless-stopped
    ports:
      - '9000:9000/tcp'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
