// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"github.com/I-m-Surrounded-by-IoT/backend/conf"
	"github.com/I-m-Surrounded-by-IoT/backend/internal/registry"
	gateway2 "github.com/I-m-Surrounded-by-IoT/backend/internal/server/gateway"
	"github.com/I-m-Surrounded-by-IoT/backend/service/gateway"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(tcpServer *conf.TcpServer, confRegistry *conf.Registry, gatewayConfig *conf.GatewayConfig, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistry(confRegistry)
	tcpHandler := gateway.NewGatewayService(gatewayConfig, registrar)
	utilsTcpServer := gateway2.NewTCPServer(tcpServer, tcpHandler)
	app := newApp(logger, utilsTcpServer, registrar)
	return app, func() {
	}, nil
}
