// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/I-m-Surrounded-by-IoT/backend/conf"
	"github.com/I-m-Surrounded-by-IoT/backend/internal/registry"
	user2 "github.com/I-m-Surrounded-by-IoT/backend/internal/server/user"
	"github.com/I-m-Surrounded-by-IoT/backend/service/user"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(grpcServer *conf.GrpcServer, confRegistry *conf.Registry, databaseConfig *conf.DatabaseConfig, logger log.Logger) (*kratos.App, func(), error) {
	userService := user.NewUserService(databaseConfig)
	grpcGatewayServer := user2.NewUserServer(grpcServer, userService)
	registrar := registry.NewRegistry(confRegistry)
	app := newApp(logger, grpcGatewayServer, registrar)
	return app, func() {
	}, nil
}
