// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package database

import (
	"github.com/I-m-Surrounded-by-IoT/backend/conf"
	"github.com/I-m-Surrounded-by-IoT/backend/internal/registry"
	database2 "github.com/I-m-Surrounded-by-IoT/backend/internal/server/database"
	"github.com/I-m-Surrounded-by-IoT/backend/service/database"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(grpcServer *conf.GrpcServer, confRegistry *conf.Registry, databaseConfig *conf.DatabaseConfig, kafkaConfig *conf.KafkaConfig, logger log.Logger) (*kratos.App, func(), error) {
	databaseService := database.NewDatabaseService(databaseConfig)
	grpcGatewayServer := database2.NewDatabaseServer(grpcServer, databaseService)
	consumerGroup := database2.NewLogConsumer(kafkaConfig)
	deviceLogConsumer := database.NewDeviceLogConsumer(databaseService)
	databaseDeviceLogConsumer := database2.NewDeviceLogConsumer(consumerGroup, deviceLogConsumer)
	registrar := registry.NewRegistry(confRegistry)
	app := newApp(logger, grpcGatewayServer, databaseDeviceLogConsumer, registrar)
	return app, func() {
	}, nil
}
